## EMISION DE GASES EFECTO INVERNADERO

In [1]:
import pandas as pd
import numpy as np

In [18]:
SEP = os.sep
dir = os.path.dirname
csv_fullpath = dir(dir(os.getcwd())) + SEP + "data" + SEP + "total contaminantes nacional.xlsx"

In [19]:
emisiones = pd.read_excel(csv_fullpath)

In [5]:
emisiones

,ANNO,SECTOR,ACTIVIDAD,DESCRIPCION,NO2,NMVOC,SOX,NH3,PM2_5,PM10,...,DIOX,BEN_A_PI,BEN_B_FL,BEN_K_FL,INDENO,PAH,HCB,PCB,Unnamed: 30,Unnamed: 31
0,2010,J_Waste,5A,Biological treatment of waste - Solid waste di...,0.012060,4.255421,0.000000,0.000000,0.005535,0.008467,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,NaN,NaN
1,2010,J_Waste,5B1,Biological treatment of waste - Composting,0.000000,0.000000,0.000000,1.087810,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,NaN,NaN
2,2010,J_Waste,5B2,Biological treatment of waste - Anaerobic dige...,0.001835,0.000000,0.000000,0.085614,0.000763,0.000763,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,NaN,NaN
3,2010,J_Waste,5C1a,Municipal waste incineration,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,NaN,NaN
4,2010,J_Waste,5C1bi,Industrial waste incineration,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,2019,J_Waste,5C2,Open burning of waste,16.561077,17.641147,0.360023,0.000000,45.122933,49.563222,...,6.000390,0.129239,0.249247,0.221553,0.0,0.600039,0.0,0.0,NaN,NaN
146,2019,J_Waste,5D1,Domestic wastewater handling,0.006856,0.071834,0.000000,0.000000,0.002848,0.002848,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,NaN,NaN
147,2019,J_Waste,5D2,Industrial wastewater handling,0.003129,0.024939,0.000000,0.000000,0.001301,0.001301,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,NaN,NaN
148,2019,J_Waste,5D3,Other wastewater handling,0.000000,0.000000,0.000000,2.110270,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,NaN,NaN
149,2019,J_Waste,5E,Other waste (please specify in IIR),0.000000,0.012628,0.000000,0.001514,1.627843,1.627843,...,16.672112,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,NaN,NaN

In [20]:
# creo una nueva columna de Total Nacional 

col_list= list(emisiones)
col_list.remove('ANNO')
col_list


emisiones['Total Nacional'] = emisiones[col_list].sum(axis=1)

In [23]:
emisiones

,ANNO,DESCRIPCION,NO2,NMVOC,SOX,NH3,PM2_5,PM10,TSP,BC,...,BEN_A_PI,BEN_B_FL,BEN_K_FL,INDENO,PAH,HCB,PCB,Unnamed: 30,Unnamed: 31,Total Nacional
0,2010,Biological treatment of waste - Solid waste di...,0.012060,4.255421,0.000000,0.000000,0.005535,0.008467,0.012314,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,NaN,NaN,4.516530
1,2010,Biological treatment of waste - Composting,0.000000,0.000000,0.000000,1.087810,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,NaN,NaN,1.087810
2,2010,Biological treatment of waste - Anaerobic dige...,0.001835,0.000000,0.000000,0.085614,0.000763,0.000763,0.000763,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,NaN,NaN,0.123630
3,2010,Municipal waste incineration,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,NaN,NaN,0.000000
4,2010,Industrial waste incineration,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,NaN,NaN,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,2019,Open burning of waste,16.561077,17.641147,0.360023,0.000000,45.122933,49.563222,51.723362,12.724667,...,0.129239,0.249247,0.221553,0.0,0.600039,0.0,0.0,NaN,NaN,1009.629469
146,2019,Domestic wastewater handling,0.006856,0.071834,0.000000,0.000000,0.002848,0.002848,0.002848,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,NaN,NaN,0.213816
147,2019,Industrial wastewater handling,0.003129,0.024939,0.000000,0.000000,0.001301,0.001301,0.001301,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,NaN,NaN,0.089758
148,2019,Other wastewater handling,0.000000,0.000000,0.000000,2.110270,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,NaN,NaN,2.110270
149,2019,Other waste (please specify in IIR),0.000000,0.012628,0.000000,0.001514,1.627843,1.627843,1.627843,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,NaN,NaN,21.655489

In [21]:
emisiones = emisiones.drop(columns=['SECTOR','ACTIVIDAD'], axis=1)

In [24]:
to_drop = emisiones.iloc[:, 2:30]
emisiones.drop(to_drop, inplace = True , axis= 1 )

In [25]:
emisiones

     ANNO                                        DESCRIPCION  Total Nacional
0    2010  Biological treatment of waste - Solid waste di...        4.516530
1    2010         Biological treatment of waste - Composting        1.087810
2    2010  Biological treatment of waste - Anaerobic dige...        0.123630
3    2010                       Municipal waste incineration        0.000000
4    2010                      Industrial waste incineration        0.000000
..    ...                                                ...             ...
145  2019                              Open burning of waste     1009.629469
146  2019                       Domestic wastewater handling        0.213816
147  2019                     Industrial wastewater handling        0.089758
148  2019                          Other wastewater handling        2.110270
149  2019                Other waste (please specify in IIR)       21.655489

[150 rows x 3 columns]

In [36]:
#voy a cambiar el nombre de la columna año 
emisiones.rename(columns={'ANNO': 'Año'}, inplace= True)

In [38]:
emisiones['Total Nacional'] = pd.Series([round(val, 2) for val in emisiones ['Total Nacional']])
emisiones['Total Nacional']

0         4.52
1         1.09
2         0.12
3         0.00
4         0.00
        ...
145    1009.63
146       0.21
147       0.09
148       2.11
149      21.66
Name: Total Nacional, Length: 150, dtype: float64

In [39]:
pivot_contami = emisiones.pivot(index='Año', columns='DESCRIPCION', values='Total Nacional')

In [40]:
pivot_contami

DESCRIPCION,Biological treatment of waste - Anaerobic digestion at biogas facilities,Biological treatment of waste - Composting,Biological treatment of waste - Solid waste disposal on land,Clinical waste incineration,Cremation,Domestic wastewater handling,Hazardous waste incineration,Industrial waste incineration,Industrial wastewater handling,Municipal waste incineration,Open burning of waste,Other waste (please specify in IIR),Other waste incineration (please specify in the IIR),Other wastewater handling,Sewage sludge incineration
Año,,,,,,,,,,,,,,,
2010,0.12,1.09,4.52,0.0,0.32,0.31,0.0,0.0,0.09,0.0,792.33,16.23,0.0,1.49,13.14
2011,0.19,1.03,4.76,0.0,0.34,0.23,0.0,0.0,0.09,0.0,826.90,19.80,0.0,1.45,13.03
2012,0.25,0.99,4.74,0.0,0.38,0.22,0.0,0.0,0.08,0.0,542.86,18.72,0.0,0.67,15.78
2013,0.41,0.91,4.66,0.0,0.39,0.22,0.0,0.0,0.08,0.0,954.47,17.95,0.0,0.67,10.58
2014,0.49,0.83,4.46,0.0,0.47,0.22,0.0,0.0,0.09,0.0,622.23,17.46,0.0,2.08,11.24
2015,0.57,0.88,4.60,0.0,0.52,0.22,0.0,0.0,0.09,0.0,797.12,17.37,0.0,2.08,11.58
2016,0.39,0.86,4.54,0.0,0.56,0.21,0.0,0.0,0.09,0.0,785.16,50.31,0.0,2.08,11.92
2017,0.51,0.86,4.52,0.0,0.55,0.21,0.0,0.0,0.09,0.0,742.75,16.83,0.0,2.09,11.61
2018,0.51,0.78,4.81,0.0,0.60,0.21,0.0,0.0,0.09,0.0,1009.63,17.52,0.0,2.09,11.56
2019,0.51,0.78,4.78,0.0,0.59,0.21,0.0,0.0,0.09,0.0,1009.63,21.66,0.0,2.11,11.44

In [ ]:
#CREO LAS DOS COLUMNAS QUE ME HACEN FALTA QUE SON AÑOS Y COMUNIDADES AUTONOMAS, Y REINICIO EL INDEX
pivot_contami['Año'] = pivot_contami.index

In [43]:
pivot_contami['Comunidad Autonoma'] = 'Total Nacional'

In [45]:
pivot_contami.reset_index(inplace=True, drop=True)

In [46]:
pivot_contami

DESCRIPCION,Biological treatment of waste - Anaerobic digestion at biogas facilities,Biological treatment of waste - Composting,Biological treatment of waste - Solid waste disposal on land,Clinical waste incineration,Cremation,Domestic wastewater handling,Hazardous waste incineration,Industrial waste incineration,Industrial wastewater handling,Municipal waste incineration,Open burning of waste,Other waste (please specify in IIR),Other waste incineration (please specify in the IIR),Other wastewater handling,Sewage sludge incineration,Año,Comunidad Autonoma
0,0.12,1.09,4.52,0.0,0.32,0.31,0.0,0.0,0.09,0.0,792.33,16.23,0.0,1.49,13.14,2010,Total Nacional
1,0.19,1.03,4.76,0.0,0.34,0.23,0.0,0.0,0.09,0.0,826.90,19.80,0.0,1.45,13.03,2011,Total Nacional
2,0.25,0.99,4.74,0.0,0.38,0.22,0.0,0.0,0.08,0.0,542.86,18.72,0.0,0.67,15.78,2012,Total Nacional
3,0.41,0.91,4.66,0.0,0.39,0.22,0.0,0.0,0.08,0.0,954.47,17.95,0.0,0.67,10.58,2013,Total Nacional
4,0.49,0.83,4.46,0.0,0.47,0.22,0.0,0.0,0.09,0.0,622.23,17.46,0.0,2.08,11.24,2014,Total Nacional
5,0.57,0.88,4.60,0.0,0.52,0.22,0.0,0.0,0.09,0.0,797.12,17.37,0.0,2.08,11.58,2015,Total Nacional
6,0.39,0.86,4.54,0.0,0.56,0.21,0.0,0.0,0.09,0.0,785.16,50.31,0.0,2.08,11.92,2016,Total Nacional
7,0.51,0.86,4.52,0.0,0.55,0.21,0.0,0.0,0.09,0.0,742.75,16.83,0.0,2.09,11.61,2017,Total Nacional
8,0.51,0.78,4.81,0.0,0.60,0.21,0.0,0.0,0.09,0.0,1009.63,17.52,0.0,2.09,11.56,2018,Total Nacional
9,0.51,0.78,4.78,0.0,0.59,0.21,0.0,0.0,0.09,0.0,1009.63,21.66,0.0,2.11,11.44,2019,Total Nacional

In [27]:
pivot_contami.columns

Index(['Biological treatment of waste - Anaerobic digestion at biogas facilities',
       'Biological treatment of waste - Composting',
       'Biological treatment of waste - Solid waste disposal on land',
       'Clinical waste incineration', 'Cremation',
       'Domestic wastewater handling', 'Hazardous waste incineration',
       'Industrial waste incineration', 'Industrial wastewater handling',
       'Municipal waste incineration', 'Open burning of waste',
       'Other waste (please specify in IIR)',
       'Other waste incineration (please specify in the IIR)',
       'Other wastewater handling', 'Sewage sludge incineration'],
      dtype='object', name='DESCRIPCION')

In [47]:
#cambio el nombre del index

emisiones_clean = pivot_contami.rename(index={'DESCRIPCION': 'Index'})

In [48]:
emisiones_clean

DESCRIPCION,Biological treatment of waste - Anaerobic digestion at biogas facilities,Biological treatment of waste - Composting,Biological treatment of waste - Solid waste disposal on land,Clinical waste incineration,Cremation,Domestic wastewater handling,Hazardous waste incineration,Industrial waste incineration,Industrial wastewater handling,Municipal waste incineration,Open burning of waste,Other waste (please specify in IIR),Other waste incineration (please specify in the IIR),Other wastewater handling,Sewage sludge incineration,Año,Comunidad Autonoma
0,0.12,1.09,4.52,0.0,0.32,0.31,0.0,0.0,0.09,0.0,792.33,16.23,0.0,1.49,13.14,2010,Total Nacional
1,0.19,1.03,4.76,0.0,0.34,0.23,0.0,0.0,0.09,0.0,826.90,19.80,0.0,1.45,13.03,2011,Total Nacional
2,0.25,0.99,4.74,0.0,0.38,0.22,0.0,0.0,0.08,0.0,542.86,18.72,0.0,0.67,15.78,2012,Total Nacional
3,0.41,0.91,4.66,0.0,0.39,0.22,0.0,0.0,0.08,0.0,954.47,17.95,0.0,0.67,10.58,2013,Total Nacional
4,0.49,0.83,4.46,0.0,0.47,0.22,0.0,0.0,0.09,0.0,622.23,17.46,0.0,2.08,11.24,2014,Total Nacional
5,0.57,0.88,4.60,0.0,0.52,0.22,0.0,0.0,0.09,0.0,797.12,17.37,0.0,2.08,11.58,2015,Total Nacional
6,0.39,0.86,4.54,0.0,0.56,0.21,0.0,0.0,0.09,0.0,785.16,50.31,0.0,2.08,11.92,2016,Total Nacional
7,0.51,0.86,4.52,0.0,0.55,0.21,0.0,0.0,0.09,0.0,742.75,16.83,0.0,2.09,11.61,2017,Total Nacional
8,0.51,0.78,4.81,0.0,0.60,0.21,0.0,0.0,0.09,0.0,1009.63,17.52,0.0,2.09,11.56,2018,Total Nacional
9,0.51,0.78,4.78,0.0,0.59,0.21,0.0,0.0,0.09,0.0,1009.63,21.66,0.0,2.11,11.44,2019,Total Nacional

In [49]:
## GUARDAMOS LA BASE DE DATOS

emisiones_clean.to_csv('emisiones_clean.csv', index=False)